// Code generated by protoc-gen-go. DO NOT EDIT.
// source: monolog.proto

package proto

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "github.com/golang/protobuf/ptypes/timestamp"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Item ...
type Item struct {
	// Types that are valid to be assigned to Item:
	//	*Item_Article
	//	*Item_Image
	Item                 isItem_Item `protobuf_oneof:"item"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *Item) Reset()         { *m = Item{} }
func (m *Item) String() string { return proto.CompactTextString(m) }
func (*Item) ProtoMessage()    {}
func (*Item) Descriptor() ([]byte, []int) {
	return fileDescriptor_9ed8d4c6d9012501, []int{0}
}

func (m *Item) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Item.Unmarshal(m, b)
}
func (m *Item) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Item.Marshal(b, m, deterministic)
}
func (m *Item) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Item.Merge(m, src)
}
func (m *Item) XXX_Size() int {
	return xxx_messageInfo_Item.Size(m)
}
func (m *Item) XXX_DiscardUnknown() {
	xxx_messageInfo_Item.DiscardUnknown(m)
}

var xxx_messageInfo_Item proto.InternalMessageInfo

type isItem_Item interface {
	isItem_Item()
}

type Item_Article struct {
	Article *Article `protobuf:"bytes,10,opt,name=article,proto3,oneof"`
}

type Item_Image struct {
	Image *Image `protobuf:"bytes,11,opt,name=image,proto3,oneof"`
}

func (*Item_Article) isItem_Item() {}

func (*Item_Image) isItem_Item() {}

func (m *Item) GetItem() isItem_Item {
	if m != nil {
		return m.Item
	}
	return nil
}

func (m *Item) GetArticle() *Article {
	if x, ok := m.GetItem().(*Item_Article); ok {
		return x.Article
	}
	return nil
}

func (m *Item) GetImage() *Image {
	if x, ok := m.GetItem().(*Item_Image); ok {
		return x.Image
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*Item) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*Item_Article)(nil),
		(*Item_Image)(nil),
	}
}

// Article ...
type Article struct {
	// UUID ...
	Uuid string `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	// Body ...
	Body                 string   `protobuf:"bytes,2,opt,name=body,proto3" json:"body,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Article) Reset()         { *m = Article{} }
func (m *Article) String() string { return proto.CompactTextString(m) }
func (*Article) ProtoMessage()    {}
func (*Article) Descriptor() ([]byte, []int) {
	return fileDescriptor_9ed8d4c6d9012501, []int{1}
}

func (m *Article) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Article.Unmarshal(m, b)
}
func (m *Article) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Article.Marshal(b, m, deterministic)
}
func (m *Article) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Article.Merge(m, src)
}
func (m *Article) XXX_Size() int {
	return xxx_messageInfo_Article.Size(m)
}
func (m *Article) XXX_DiscardUnknown() {
	xxx_messageInfo_Article.DiscardUnknown(m)
}

var xxx_messageInfo_Article proto.InternalMessageInfo

func (m *Article) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

func (m *Article) GetBody() string {
	if m != nil {
		return m.Body
	}
	return ""
}

// Image ...
type Image struct {
	// UUID ...
	Uuid string `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	// URL ...
	Url                  string   `protobuf:"bytes,2,opt,name=url,proto3" json:"url,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Image) Reset()         { *m = Image{} }
func (m *Image) String() string { return proto.CompactTextString(m) }
func (*Image) ProtoMessage()    {}
func (*Image) Descriptor() ([]byte, []int) {
	return fileDescriptor_9ed8d4c6d9012501, []int{2}
}

func (m *Image) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Image.Unmarshal(m, b)
}
func (m *Image) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Image.Marshal(b, m, deterministic)
}
func (m *Image) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Image.Merge(m, src)
}
func (m *Image) XXX_Size() int {
	return xxx_messageInfo_Image.Size(m)
}
func (m *Image) XXX_DiscardUnknown() {
	xxx_messageInfo_Image.DiscardUnknown(m)
}

var xxx_messageInfo_Image proto.InternalMessageInfo

func (m *Image) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

func (m *Image) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

// Insert ...
type Insert struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Insert) Reset()         { *m = Insert{} }
func (m *Insert) String() string { return proto.CompactTextString(m) }
func (*Insert) ProtoMessage()    {}
func (*Insert) Descriptor() ([]byte, []int) {
	return fileDescriptor_9ed8d4c6d9012501, []int{3}
}

func (m *Insert) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Insert.Unmarshal(m, b)
}
func (m *Insert) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Insert.Marshal(b, m, deterministic)
}
func (m *Insert) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Insert.Merge(m, src)
}
func (m *Insert) XXX_Size() int {
	return xxx_messageInfo_Insert.Size(m)
}
func (m *Insert) XXX_DiscardUnknown() {
	xxx_messageInfo_Insert.DiscardUnknown(m)
}

var xxx_messageInfo_Insert proto.InternalMessageInfo

// Request ...
type Insert_Request struct {
	Item                 *Item    `protobuf:"bytes,1,opt,name=item,proto3" json:"item,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Insert_Request) Reset()         { *m = Insert_Request{} }
func (m *Insert_Request) String() string { return proto.CompactTextString(m) }
func (*Insert_Request) ProtoMessage()    {}
func (*Insert_Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_9ed8d4c6d9012501, []int{3, 0}
}

func (m *Insert_Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Insert_Request.Unmarshal(m, b)
}
func (m *Insert_Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Insert_Request.Marshal(b, m, deterministic)
}
func (m *Insert_Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Insert_Request.Merge(m, src)
}
func (m *Insert_Request) XXX_Size() int {
	return xxx_messageInfo_Insert_Request.Size(m)
}
func (m *Insert_Request) XXX_DiscardUnknown() {
	xxx_messageInfo_Insert_Request.DiscardUnknown(m)
}

var xxx_messageInfo_Insert_Request proto.InternalMessageInfo

func (m *Insert_Request) GetItem() *Item {
	if m != nil {
		return m.Item
	}
	return nil
}

// Response ...
type Insert_Response struct {
	Uuid                 string   `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Insert_Response) Reset()         { *m = Insert_Response{} }
func (m *Insert_Response) String() string { return proto.CompactTextString(m) }
func (*Insert_Response) ProtoMessage()    {}
func (*Insert_Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_9ed8d4c6d9012501, []int{3, 1}
}

func (m *Insert_Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Insert_Response.Unmarshal(m, b)
}
func (m *Insert_Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Insert_Response.Marshal(b, m, deterministic)
}
func (m *Insert_Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Insert_Response.Merge(m, src)
}
func (m *Insert_Response) XXX_Size() int {
	return xxx_messageInfo_Insert_Response.Size(m)
}
func (m *Insert_Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Insert_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Insert_Response proto.InternalMessageInfo

func (m *Insert_Response) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

// Update ...
type Update struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Update) Reset()         { *m = Update{} }
func (m *Update) String() string { return proto.CompactTextString(m) }
func (*Update) ProtoMessage()    {}
func (*Update) Descriptor() ([]byte, []int) {
	return fileDescriptor_9ed8d4c6d9012501, []int{4}
}

func (m *Update) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Update.Unmarshal(m, b)
}
func (m *Update) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Update.Marshal(b, m, deterministic)
}
func (m *Update) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Update.Merge(m, src)
}
func (m *Update) XXX_Size() int {
	return xxx_messageInfo_Update.Size(m)
}
func (m *Update) XXX_DiscardUnknown() {
	xxx_messageInfo_Update.DiscardUnknown(m)
}

var xxx_messageInfo_Update proto.InternalMessageInfo

// Request ...
type Update_Request struct {
	Item                 *Item    `protobuf:"bytes,1,opt,name=item,proto3" json:"item,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Update_Request) Reset()         { *m = Update_Request{} }
func (m *Update_Request) String() string { return proto.CompactTextString(m) }
func (*Update_Request) ProtoMessage()    {}
func (*Update_Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_9ed8d4c6d9012501, []int{4, 0}
}

func (m *Update_Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Update_Request.Unmarshal(m, b)
}
func (m *Update_Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Update_Request.Marshal(b, m, deterministic)
}
func (m *Update_Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Update_Request.Merge(m, src)
}
func (m *Update_Request) XXX_Size() int {
	return xxx_messageInfo_Update_Request.Size(m)
}
func (m *Update_Request) XXX_DiscardUnknown() {
	xxx_messageInfo_Update_Request.DiscardUnknown(m)
}

var xxx_messageInfo_Update_Request proto.InternalMessageInfo

func (m *Update_Request) GetItem() *Item {
	if m != nil {
		return m.Item
	}
	return nil
}

// Response ...
type Update_Response struct {
	Uuid                 string   `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Update_Response) Reset()         { *m = Update_Response{} }
func (m *Update_Response) String() string { return proto.CompactTextString(m) }
func (*Update_Response) ProtoMessage()    {}
func (*Update_Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_9ed8d4c6d9012501, []int{4, 1}
}

func (m *Update_Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Update_Response.Unmarshal(m, b)
}
func (m *Update_Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Update_Response.Marshal(b, m, deterministic)
}
func (m *Update_Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Update_Response.Merge(m, src)
}
func (m *Update_Response) XXX_Size() int {
	return xxx_messageInfo_Update_Response.Size(m)
}
func (m *Update_Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Update_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Update_Response proto.InternalMessageInfo

func (m *Update_Response) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

// Empty ...
type Empty struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Empty) Reset()         { *m = Empty{} }
func (m *Empty) String() string { return proto.CompactTextString(m) }
func (*Empty) ProtoMessage()    {}
func (*Empty) Descriptor() ([]byte, []int) {
	return fileDescriptor_9ed8d4c6d9012501, []int{5}
}

func (m *Empty) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Empty.Unmarshal(m, b)
}
func (m *Empty) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Empty.Marshal(b, m, deterministic)
}
func (m *Empty) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Empty.Merge(m, src)
}
func (m *Empty) XXX_Size() int {
	return xxx_messageInfo_Empty.Size(m)
}
func (m *Empty) XXX_DiscardUnknown() {
	xxx_messageInfo_Empty.DiscardUnknown(m)
}

var xxx_messageInfo_Empty proto.InternalMessageInfo

func init() {
	proto.RegisterType((*Item)(nil), "proto.Item")
	proto.RegisterType((*Article)(nil), "proto.Article")
	proto.RegisterType((*Image)(nil), "proto.Image")
	proto.RegisterType((*Insert)(nil), "proto.Insert")
	proto.RegisterType((*Insert_Request)(nil), "proto.Insert.Request")
	proto.RegisterType((*Insert_Response)(nil), "proto.Insert.Response")
	proto.RegisterType((*Update)(nil), "proto.Update")
	proto.RegisterType((*Update_Request)(nil), "proto.Update.Request")
	proto.RegisterType((*Update_Response)(nil), "proto.Update.Response")
	proto.RegisterType((*Empty)(nil), "proto.Empty")
}

func init() { proto.RegisterFile("monolog.proto", fileDescriptor_9ed8d4c6d9012501) }

var fileDescriptor_9ed8d4c6d9012501 = []byte{
	// 292 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x91, 0xcf, 0x4b, 0x84, 0x40,
	0x14, 0xc7, 0xd7, 0xf2, 0x47, 0x3d, 0x2b, 0x62, 0xa0, 0x10, 0x0f, 0xed, 0x22, 0x1d, 0x96, 0x85,
	0x5c, 0xb2, 0xc3, 0x9e, 0x0b, 0x82, 0xf5, 0xd0, 0x65, 0xa8, 0x7b, 0x9a, 0x2f, 0x11, 0x1c, 0xc7,
	0xf4, 0x79, 0x58, 0xfa, 0xe7, 0xc3, 0x19, 0x67, 0x0f, 0xb5, 0xc7, 0x4e, 0xbe, 0xf7, 0x99, 0xef,
	0x8f, 0x07, 0xc2, 0xb9, 0x90, 0x8d, 0xac, 0x65, 0x19, 0xb7, 0x9d, 0x24, 0xc9, 0x1c, 0xf5, 0x09,
	0xe7, 0xa5, 0x94, 0x65, 0x8d, 0x6b, 0xb5, 0xe5, 0xc3, 0xe7, 0x9a, 0x2a, 0x81, 0x3d, 0x65, 0xa2,
	0xd5, 0xba, 0xe8, 0x1d, 0xec, 0x94, 0x50, 0xb0, 0x15, 0x78, 0x59, 0x47, 0xd5, 0x47, 0x8d, 0x01,
	0x2c, 0xac, 0xa5, 0x9f, 0x5c, 0x68, 0x41, 0xfc, 0xa8, 0xe9, 0x76, 0xc6, 0x8d, 0x80, 0xdd, 0x82,
	0x53, 0x89, 0xac, 0xc4, 0xc0, 0x57, 0xca, 0xb3, 0x49, 0x99, 0x8e, 0x6c, 0x3b, 0xe3, 0xfa, 0xf1,
	0xc9, 0x05, 0xbb, 0x22, 0x14, 0xd1, 0x3d, 0x78, 0x53, 0x06, 0x63, 0x60, 0x0f, 0x43, 0x55, 0x04,
	0xd6, 0xc2, 0x5a, 0x9e, 0x72, 0x35, 0x8f, 0x2c, 0x97, 0xc5, 0x2e, 0x38, 0xd2, 0x6c, 0x9c, 0xa3,
	0x3b, 0x70, 0x54, 0xd8, 0x41, 0xc3, 0x25, 0x1c, 0x0f, 0x5d, 0x3d, 0xe9, 0xc7, 0x31, 0x7a, 0x05,
	0x37, 0x6d, 0x7a, 0xec, 0x28, 0x5c, 0x81, 0xc7, 0xf1, 0x6b, 0xc0, 0x9e, 0xd8, 0x5c, 0xd7, 0x2b,
	0xab, 0x9f, 0xf8, 0xe6, 0x46, 0x42, 0xc1, 0xd5, 0x43, 0x78, 0x03, 0x27, 0x1c, 0xfb, 0x56, 0x36,
	0xfd, 0xc1, 0x9e, 0x31, 0xf5, 0xad, 0x2d, 0x32, 0xc2, 0x7f, 0x4d, 0xf5, 0xc0, 0x79, 0x16, 0x2d,
	0xed, 0x92, 0x6f, 0xf0, 0x5e, 0xf4, 0x1f, 0x63, 0x1b, 0x73, 0x3f, 0xbb, 0x32, 0x81, 0x6a, 0x8d,
	0xa7, 0xd6, 0xf0, 0xfa, 0x37, 0x9e, 0x0a, 0x36, 0xe6, 0xc4, 0xbd, 0x51, 0xaf, 0x7f, 0x8c, 0x7b,
	0xac, 0x8d, 0xb9, 0xab, 0xf0, 0xc3, 0x4f, 0x00, 0x00, 0x00, 0xff, 0xff, 0xb5, 0xe9, 0x57, 0xc0,
	0x35, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// MonologClient is the client API for Monolog service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MonologClient interface {
	// Insert ...
	Insert(ctx context.Context, in *Insert_Request, opts ...grpc.CallOption) (*Insert_Response, error)
	// Update ...
	Update(ctx context.Context, in *Update_Request, opts ...grpc.CallOption) (*Update_Response, error)
}

type monologClient struct {
	cc grpc.ClientConnInterface
}

func NewMonologClient(cc grpc.ClientConnInterface) MonologClient {
	return &monologClient{cc}
}

func (c *monologClient) Insert(ctx context.Context, in *Insert_Request, opts ...grpc.CallOption) (*Insert_Response, error) {
	out := new(Insert_Response)
	err := c.cc.Invoke(ctx, "/proto.Monolog/Insert", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *monologClient) Update(ctx context.Context, in *Update_Request, opts ...grpc.CallOption) (*Update_Response, error) {
	out := new(Update_Response)
	err := c.cc.Invoke(ctx, "/proto.Monolog/Update", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MonologServer is the server API for Monolog service.
type MonologServer interface {
	// Insert ...
	Insert(context.Context, *Insert_Request) (*Insert_Response, error)
	// Update ...
	Update(context.Context, *Update_Request) (*Update_Response, error)
}

// UnimplementedMonologServer can be embedded to have forward compatible implementations.
type UnimplementedMonologServer struct {
}

func (*UnimplementedMonologServer) Insert(ctx context.Context, req *Insert_Request) (*Insert_Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Insert not implemented")
}
func (*UnimplementedMonologServer) Update(ctx context.Context, req *Update_Request) (*Update_Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Update not implemented")
}

func RegisterMonologServer(s *grpc.Server, srv MonologServer) {
	s.RegisterService(&_Monolog_serviceDesc, srv)
}

func _Monolog_Insert_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Insert_Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MonologServer).Insert(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Monolog/Insert",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MonologServer).Insert(ctx, req.(*Insert_Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _Monolog_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Update_Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MonologServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Monolog/Update",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MonologServer).Update(ctx, req.(*Update_Request))
	}
	return interceptor(ctx, in, info, handler)
}

var _Monolog_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.Monolog",
	HandlerType: (*MonologServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Insert",
			Handler:    _Monolog_Insert_Handler,
		},
		{
			MethodName: "Update",
			Handler:    _Monolog_Update_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "monolog.proto",
}
